export const newsProseClassName = [
  "max-w-none text-[1.02rem] leading-8 text-foreground/90",
  "[&_h2]:mt-12 [&_h2]:text-2xl [&_h2]:font-semibold [&_h2]:tracking-tight",
  "[&_h3]:mt-8 [&_h3]:text-xl [&_h3]:font-semibold",
  "[&_p]:mt-5",
  "[&_a]:font-medium [&_a]:text-foreground [&_a]:underline [&_a]:decoration-border [&_a]:underline-offset-4",
  "[&_ul]:mt-5 [&_ul]:list-disc [&_ul]:pl-6",
  "[&_ol]:mt-5 [&_ol]:list-decimal [&_ol]:pl-6",
  "[&_li]:mt-2",
  "[&_blockquote]:mt-8 [&_blockquote]:border-l-2 [&_blockquote]:border-border [&_blockquote]:pl-5 [&_blockquote]:italic [&_blockquote]:text-foreground/80",
  "[&_pre]:mt-8 [&_pre]:overflow-x-auto [&_pre]:rounded-2xl [&_pre]:border [&_pre]:border-border/70 [&_pre]:bg-muted/70 [&_pre]:p-4",
  "[&_code]:break-words [&_code]:rounded-md [&_code]:bg-muted/70 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:text-sm",
  "[&_pre_code]:bg-transparent [&_pre_code]:px-0 [&_pre_code]:py-0",
  "[&_img]:mt-8 [&_img]:w-full [&_img]:rounded-3xl [&_img]:border [&_img]:border-border/70 [&_img]:object-cover",
  "[&_table]:mt-8 [&_table]:block [&_table]:w-full [&_table]:overflow-x-auto",
  "[&_thead]:border-b [&_thead]:border-border",
  "[&_th]:px-3 [&_th]:py-2 [&_th]:text-left [&_th]:text-sm [&_th]:font-semibold",
  "[&_td]:px-3 [&_td]:py-2 [&_td]:text-sm",
].join(" ");
